# Based on https://github.com/khulnasoft/ml-buildkit/blob/v0.6.6/workflows/build-pipeline.yml
name: build-pipeline

on:
  workflow_dispatch:
    inputs:
      build_args:
        description: "Arguments passed to build script"
        required: false
        default: "--make --force"
      working_directory:
        description: "Working directory from where the build command is run"
        required: false
        default: "."
  push:
    branches:
      - main

env:
  BUILD_ARGS: ${{ github.event.inputs?.build_args || secrets.BUILD_ARGS }}
  WORKING_DIRECTORY: ${{ github.event.inputs?.working_directory || secrets.WORKING_DIRECTORY }}
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true # TODO: only needed until act supports the new way

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: set-host-ip
        run: echo "::set-env name=_HOST_IP::$(hostname -I | cut -d ' ' -f 1)"
      - uses: actions/checkout@v2
      - name: run-build-scripts
        uses: ./.github/actions/build-environment
        with:
          build_args: ${{ env.BUILD_ARGS }}
          working_directory: ${{ env.WORKING_DIRECTORY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
